# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "alfe-theme-app"
client_id = "0c813ca03422d28fb054153330a6811a"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "clevelandrocks.myshopify.com"
